// templates/frontend-nextjs/scaffold/src/app/reports/page.tsx
'use client';

import { useReports } from '@/features/reports/use-reports';
import Link from 'next/link';

export default function ReportsPage() {
  const { data: reports, isLoading, error } = useReports();

  if (isLoading) {
    return <div className="p-8">Loading reports...</div>;
  }

  if (error) {
    return <div className="p-8 text-red-600">Error loading reports</div>;
  }

  return (
    <div className="min-h-screen p-8">
      <div className="max-w-4xl mx-auto">
        <div className="mb-6">
          <Link href="/" className="text-blue-600 hover:underline">
            ← Back to home
          </Link>
        </div>
        <h1 className="text-3xl font-bold mb-6">Reports</h1>
        <div className="space-y-4">
          {reports && reports.length > 0 ? (
            reports.map((report) => (
              <div key={report.id} className="p-4 border rounded">
                <h2 className="font-semibold">{report.name}</h2>
                <p className="text-sm text-gray-600">{report.description}</p>
              </div>
            ))
          ) : (
            <p className="text-gray-600">No reports available</p>
          )}
        </div>
      </div>
    </div>
  );
}

// templates/frontend-sveltekit/scaffold/src/routes/reports/+page.svelte
<script lang="ts">
	import { AppShell, AppBar } from '@skeletonlabs/skeleton-svelte';
	import { createQuery } from '@tanstack/svelte-query';
	import { fetchReports } from '$features/reports/report-service';

	const reportsQuery = createQuery({
		queryKey: ['reports'],
		queryFn: fetchReports
	});
</script>

<svelte:head>
	<title>Reports - {{projectName}}</title>
</svelte:head>

<AppShell>
	{#snippet appBar()}
		<AppBar>
			<svelte:fragment slot="lead">
				<a href="/" class="text-xl font-bold">{{projectName}}</a>
			</svelte:fragment>
		</AppBar>
	{/snippet}

	<div class="container mx-auto p-8">
		<div class="max-w-4xl mx-auto space-y-6">
			<div class="mb-6">
				<a href="/" class="anchor">← Back to home</a>
			</div>

			<h1 class="h1">Reports</h1>

			{#if $reportsQuery.isLoading}
				<div class="card p-4">Loading reports...</div>
			{:else if $reportsQuery.error}
				<div class="card variant-ghost-error p-4">
					Error loading reports: {$reportsQuery.error.message}
				</div>
			{:else if $reportsQuery.data && $reportsQuery.data.length > 0}
				<div class="space-y-4">
					{#each $reportsQuery.data as report (report.id)}
						<div class="card p-4">
							<h2 class="h4">{report.name}</h2>
							<p class="text-sm text-surface-600-300">{report.description}</p>
						</div>
					{/each}
				</div>
			{:else}
				<div class="card p-4 text-center text-surface-600-300">
					No reports available
				</div>
			{/if}
		</div>
	</div>
</AppShell>
